import Foundation
import SwiftData

// MARK: - WorkoutSchedule

/// A recurring weekly training plan generated by WorkoutScheduleGeneratorService.
/// Sessions describe the weekly template; concrete Workout objects are created
/// when the user starts a session.
@Model
final class WorkoutSchedule {
    var uuid: String = UUID().uuidString
    var createdAt: Date = Date()
    var title: String = ""
    var goalRaw: String = WorkoutScheduleGoal.generalFitness.rawValue
    var experienceRaw: String = WorkoutExperienceLevel.intermediate.rawValue
    var daysPerWeek: Int = 3
    var sessionLengthMinutes: Int = 60
    var equipmentRaw: [String] = []
    /// Calendar weekdays (1 = Sunday ... 7 = Saturday).
    var preferredWeekdays: [Int] = []
    var startDate: Date = Date()
    var endDate: Date?
    var syncToCalendar: Bool = false
    var calendarEventIds: [String] = []
    /// Free-text limitations/injuries the user entered when generating.
    var limitations: String = ""
    /// Plan-level progression / deload guidance shown in the preview and detail.
    var progressionNote: String = ""
    @Relationship(deleteRule: .cascade) var sessions: [WorkoutScheduleSession]? = []

    var goal: WorkoutScheduleGoal {
        get { WorkoutScheduleGoal(rawValue: goalRaw) ?? .generalFitness }
        set { goalRaw = newValue.rawValue }
    }
    var experience: WorkoutExperienceLevel {
        get { WorkoutExperienceLevel(rawValue: experienceRaw) ?? .intermediate }
        set { experienceRaw = newValue.rawValue }
    }
    var equipment: [Equipment] {
        get { equipmentRaw.compactMap { Equipment(rawValue: $0) } }
        set { equipmentRaw = newValue.map(\.rawValue) }
    }
    var sessionList: [WorkoutScheduleSession] {
        (sessions ?? []).sorted { $0.weekday < $1.weekday }
    }
    var isActive: Bool {
        let today = Date().startOfDay
        if startDate.startOfDay > today { return true } // upcoming counts as active
        if let endDate, endDate.startOfDay < today { return false }
        return true
    }

    init(title: String,
         goal: WorkoutScheduleGoal,
         experience: WorkoutExperienceLevel,
         daysPerWeek: Int,
         sessionLengthMinutes: Int,
         equipment: [Equipment],
         preferredWeekdays: [Int],
         startDate: Date,
         endDate: Date? = nil,
         syncToCalendar: Bool = false,
         limitations: String = "",
         progressionNote: String = "") {
        self.createdAt = .now
        self.title = title
        self.goalRaw = goal.rawValue
        self.experienceRaw = experience.rawValue
        self.daysPerWeek = daysPerWeek
        self.sessionLengthMinutes = sessionLengthMinutes
        self.equipmentRaw = equipment.map(\.rawValue)
        self.preferredWeekdays = preferredWeekdays
        self.startDate = startDate
        self.endDate = endDate
        self.syncToCalendar = syncToCalendar
        self.limitations = limitations
        self.progressionNote = progressionNote
        self.sessions = []
    }
}

// MARK: - WorkoutScheduleSession

@Model
final class WorkoutScheduleSession {
    var uuid: String = UUID().uuidString
    /// Calendar weekday (1 = Sunday ... 7 = Saturday).
    var weekday: Int = 2
    /// First occurrence, carrying the session's time of day.
    var date: Date?
    var title: String = ""
    var workoutTypeRaw: String = WorkoutType.fullBody.rawValue
    var estimatedDurationMinutes: Int = 60
    /// JSON-encoded [PlannedExercise].
    var exercisePlanJSON: String = "[]"
    var calendarEventId: String?
    var reminderEnabled: Bool = true
    /// Day key (yyyy-MM-dd) of the most recent Workout created from this session,
    /// used to avoid duplicating today's workout.
    var generatedWorkoutId: String?
    var schedule: WorkoutSchedule?

    var workoutType: WorkoutType {
        get { WorkoutType(rawValue: workoutTypeRaw) ?? .fullBody }
        set { workoutTypeRaw = newValue.rawValue }
    }

    var plannedExercises: [PlannedExercise] {
        guard let data = exercisePlanJSON.data(using: .utf8),
              let plan = try? JSONDecoder().decode([PlannedExercise].self, from: data) else { return [] }
        return plan
    }

    init(weekday: Int,
         date: Date? = nil,
         title: String,
         workoutType: WorkoutType,
         estimatedDurationMinutes: Int,
         plannedExercises: [PlannedExercise],
         reminderEnabled: Bool = true) {
        self.weekday = weekday
        self.date = date
        self.title = title
        self.workoutTypeRaw = workoutType.rawValue
        self.estimatedDurationMinutes = estimatedDurationMinutes
        if let data = try? JSONEncoder().encode(plannedExercises),
           let json = String(data: data, encoding: .utf8) {
            self.exercisePlanJSON = json
        }
        self.reminderEnabled = reminderEnabled
    }
}

// MARK: - PlannedExercise

/// Codable exercise plan stored inside WorkoutScheduleSession.exercisePlanJSON.
/// Converted into real Exercise/WorkoutSet objects when a session starts.
struct PlannedExercise: Codable, Hashable, Identifiable {
    var name: String
    var sets: Int
    var reps: Int
    var restSeconds: Int
    var targetRPE: Double
    var equipmentRaw: String
    var patternRaw: String
    var musclesRaw: [String]
    var note: String

    var id: String { name }

    var equipment: Equipment { Equipment(rawValue: equipmentRaw) ?? .bodyweight }
    var pattern: MovementPattern { MovementPattern(rawValue: patternRaw) ?? .core }
    var muscles: [MuscleGroup] { musclesRaw.compactMap { MuscleGroup(rawValue: $0) } }

    /// Build a real Exercise (with planned, uncompleted sets) from this plan.
    func makeExercise(order: Int) -> Exercise {
        let exercise = Exercise(
            name: name,
            muscleGroups: muscles,
            movementPattern: pattern,
            equipment: equipment,
            order: order,
            restSeconds: restSeconds,
            targetRPE: targetRPE,
            notes: note)
        for index in 0..<max(1, sets) {
            exercise.sets?.append(WorkoutSet(order: index, reps: reps))
        }
        return exercise
    }

    /// Human summary, e.g. "4 × 8 · rest 120s".
    var summary: String { "\(sets) × \(reps) · rest \(restSeconds)s" }
}
