import Foundation

/// A menu-item template: the minimal human description we synthesize a full,
/// scored `MenuItem` from. Deliberately just name + description + category +
/// price, so items are generated by the reusable estimator, not hardcoded.
struct DishTemplate {
    var name: String
    var description: String
    var category: MenuCategory
    var price: Double
    /// Chains publish official nutrition; when true we freeze the estimate as
    /// "official" so the app can demonstrate the official-vs-estimated split.
    var official: Bool = false
}

/// Offline sample restaurant + menu catalogue used by the mock providers. Spans
/// several cities worldwide so search, distance, currency, and region handling
/// all have something real to work against.
enum SampleMenuData {

    // MARK: Restaurants

    static let restaurants: [Restaurant] = [
        make("greenfuel", "Green Fuel Kitchen", ["Healthy", "Bowls"], "210 W 40th St", "New York", "United States",
             40.7549, -73.9880, .moderate, "USD", official: false, avg: 78, diet: [.vegetarian, .vegan, .glutenFree]),
        make("brooklynburger", "Brooklyn Burger Co.", ["American", "Burgers"], "88 Bedford Ave", "Brooklyn", "United States",
             40.7182, -73.9570, .moderate, "USD", official: false, avg: 46, diet: [.vegetarian]),
        make("burgerbarn", "Burger Barn", ["American", "Fast Food"], "500 8th Ave", "New York", "United States",
             40.7530, -73.9930, .budget, "USD", official: true, avg: 42, diet: [.vegetarian]),
        make("trattoria", "Trattoria Roma", ["Italian"], "45 Mulberry St", "New York", "United States",
             40.7190, -73.9977, .premium, "USD", official: false, avg: 55, diet: [.vegetarian]),
        make("freshbowl", "FreshBowl", ["Healthy", "Salads"], "12 Soho Sq", "London", "United Kingdom",
             51.5155, -0.1320, .moderate, "GBP", official: true, avg: 80, diet: [.vegetarian, .vegan]),
        make("spice", "Spice Route", ["Indian"], "77 Brick Lane", "London", "United Kingdom",
             51.5215, -0.0719, .moderate, "GBP", official: false, avg: 60, diet: [.vegetarian]),
        make("sakura", "Sakura Sushi", ["Japanese", "Sushi"], "3-1 Ginza", "Tokyo", "Japan",
             35.6717, 139.7640, .premium, "JPY", official: false, avg: 68, diet: [.vegetarian]),
        make("tokyoramen", "Tokyo Ramen Bar", ["Japanese", "Ramen"], "1-5 Shinjuku", "Tokyo", "Japan",
             35.6938, 139.7034, .budget, "JPY", official: false, avg: 50, diet: [.vegetarian]),
        make("goldendragon", "Golden Dragon", ["Chinese"], "620 Grant Ave", "San Francisco", "United States",
             37.7946, -122.4066, .moderate, "USD", official: false, avg: 58, diet: [.vegetarian]),
        make("casa", "Casa Verde", ["Mexican"], "1420 Sunset Blvd", "Los Angeles", "United States",
             34.0780, -118.2606, .moderate, "USD", official: false, avg: 57, diet: [.vegetarian, .vegan]),
        make("bangkok", "Bangkok Street", ["Thai"], "44 Sukhumvit Rd", "Bangkok", "Thailand",
             13.7380, 100.5608, .budget, "THB", official: false, avg: 59, diet: [.vegetarian]),
        make("cornercafe", "Corner Café", ["Café", "Breakfast"], "18 Rue de Rivoli", "Paris", "France",
             48.8558, 2.3588, .moderate, "EUR", official: false, avg: 62, diet: [.vegetarian]),
        make("olive", "Olive & Za", ["Mediterranean"], "55 King St", "Sydney", "Australia",
             -33.8690, 151.2050, .moderate, "AUD", official: false, avg: 72, diet: [.vegetarian, .vegan]),
        // Publishes no readable menu — exercises the "menu unavailable" path.
        make("hiddentable", "The Hidden Table", ["Fine Dining"], "9 Torstraße", "Berlin", "Germany",
             52.5290, 13.4010, .luxury, "EUR", official: false, avg: nil, diet: []),
    ]

    private static func make(_ id: String, _ name: String, _ cuisines: [String], _ address: String,
                             _ city: String, _ country: String, _ lat: Double, _ lon: Double,
                             _ price: PriceLevel, _ currency: String, official: Bool, avg: Double?,
                             diet: [DietaryTag]) -> Restaurant {
        Restaurant(id: "sample:" + id, name: name, cuisines: cuisines, address: address, city: city,
                   country: country, location: GeoPoint(latitude: lat, longitude: lon),
                   priceLevel: price, hours: .everyDay(open: 8 * 60, close: 22 * 60),
                   phone: nil, website: nil, currencyCode: currency,
                   hasOfficialNutrition: official, averageMenuHealthScore: avg,
                   providerName: "Locked In Sample", dietaryTags: diet, photoAssetName: nil)
    }

    /// Default origin used when the user hasn't shared a location and hasn't set
    /// a manual one — Midtown Manhattan, so nearby has content out of the box.
    static let defaultOrigin = GeoPoint(latitude: 40.7549, longitude: -73.9880)

    // MARK: Menu templates by cuisine

    private static func templates(forCuisine tag: String, official: Bool) -> [DishTemplate] {
        switch tag {
        case "healthbowl":
            return [
                DishTemplate(name: "Grilled Chicken Power Bowl", description: "Grilled chicken breast, brown rice, broccoli, avocado, and a light vinaigrette", category: .mains, price: 14.5, official: official),
                DishTemplate(name: "Salmon Poke Bowl", description: "Raw salmon, white rice, cucumber, and avocado", category: .mains, price: 16, official: official),
                DishTemplate(name: "Steamed Tofu & Veg Bowl", description: "Steamed tofu, steamed broccoli, and brown rice with no oil", category: .mains, price: 12),
                DishTemplate(name: "Quinoa Chickpea Salad", description: "Quinoa, salad greens, chickpeas, feta, and vinaigrette", category: .salads, price: 11),
                DishTemplate(name: "Green Smoothie", description: "Spinach and milk smoothie", category: .drinks, price: 7),
            ]
        case "american":
            return [
                DishTemplate(name: "Classic Cheeseburger", description: "Grilled beef patty, cheddar cheese, brioche bun, lettuce, and tomato", category: .mains, price: 12, official: official),
                DishTemplate(name: "Crispy Chicken Sandwich", description: "Fried chicken, bun, mayo, and lettuce", category: .mains, price: 11, official: official),
                DishTemplate(name: "French Fries", description: "Deep-fried potato fries", category: .sides, price: 5, official: official),
                DishTemplate(name: "Garden Salad", description: "Salad greens, tomato, cucumber, and ranch", category: .salads, price: 8),
                DishTemplate(name: "Chocolate Brownie", description: "Warm baked chocolate brownie", category: .desserts, price: 6),
                DishTemplate(name: "Cola", description: "Regular soda", category: .drinks, price: 3, official: official),
            ]
        case "italian":
            return [
                DishTemplate(name: "Spaghetti Bolognese", description: "Pasta with ground beef tomato sauce and parmesan", category: .mains, price: 15),
                DishTemplate(name: "Margherita Pizza", description: "Baked dough with mozzarella and tomato", category: .mains, price: 14),
                DishTemplate(name: "Caesar Salad", description: "Salad greens, parmesan, and caesar dressing", category: .salads, price: 10),
                DishTemplate(name: "Tiramisu", description: "Coffee cake dessert", category: .desserts, price: 7),
            ]
        case "japanese":
            return [
                DishTemplate(name: "Salmon Sashimi", description: "Raw salmon, no oil", category: .mains, price: 18),
                DishTemplate(name: "Chicken Katsu Curry", description: "Deep-fried breaded chicken with white rice and curry sauce", category: .mains, price: 15),
                DishTemplate(name: "Teriyaki Chicken Bowl", description: "Grilled chicken, white rice, and teriyaki sauce", category: .mains, price: 14),
                DishTemplate(name: "Miso Soup", description: "Tofu soup", category: .soups, price: 4),
            ]
        case "ramen":
            return [
                DishTemplate(name: "Tonkotsu Ramen", description: "Pasta noodles in pork broth with egg and pork", category: .mains, price: 13),
                DishTemplate(name: "Vegetable Fried Rice", description: "Fried rice with mixed vegetables and egg", category: .mains, price: 10),
            ]
        case "chinese":
            return [
                DishTemplate(name: "Kung Pao Chicken", description: "Stir-fried chicken with mixed vegetables and chili oil", category: .mains, price: 13),
                DishTemplate(name: "Steamed Fish with Chilli Oil", description: "Steamed white fish topped with chilli oil", category: .mains, price: 17),
                DishTemplate(name: "Vegetable Fried Rice", description: "Fried rice with mixed vegetables and egg", category: .mains, price: 10),
                DishTemplate(name: "Sweet and Sour Pork", description: "Deep-fried pork with sweet chili sauce", category: .mains, price: 13),
            ]
        case "indian":
            return [
                DishTemplate(name: "Chicken Tikka Masala", description: "Grilled chicken in curry sauce with naan", category: .mains, price: 14),
                DishTemplate(name: "Dal Tadka", description: "Lentils with spices", category: .mains, price: 10),
                DishTemplate(name: "Paneer Butter Masala", description: "Paneer in butter curry sauce with naan", category: .mains, price: 12),
                DishTemplate(name: "Vegetable Samosa", description: "Deep-fried pastry with potato", category: .sides, price: 5),
            ]
        case "mexican":
            return [
                DishTemplate(name: "Chicken Burrito Bowl", description: "Grilled chicken, white rice, black beans, salsa, cheese, and guacamole", category: .mains, price: 12),
                DishTemplate(name: "Beef Tacos", description: "Ground beef, tortilla, cheese, and salsa", category: .mains, price: 11),
                DishTemplate(name: "Guacamole & Chips", description: "Guacamole with deep-fried tortilla chips", category: .sides, price: 7),
            ]
        case "thai":
            return [
                DishTemplate(name: "Pad Thai", description: "Stir-fried noodles with shrimp and egg", category: .mains, price: 13),
                DishTemplate(name: "Green Curry", description: "Chicken green curry with white rice", category: .mains, price: 14),
                DishTemplate(name: "Tom Yum Soup", description: "Spicy shrimp soup", category: .soups, price: 9),
            ]
        case "cafe":
            return [
                DishTemplate(name: "Avocado Toast", description: "Sourdough toast with avocado", category: .breakfast, price: 9),
                DishTemplate(name: "Scrambled Eggs on Toast", description: "Two scrambled eggs with buttered toast", category: .breakfast, price: 8),
                DishTemplate(name: "Latte", description: "Coffee with milk", category: .drinks, price: 4),
                DishTemplate(name: "Blueberry Muffin", description: "Baked muffin", category: .desserts, price: 4),
            ]
        case "mediterranean":
            return [
                DishTemplate(name: "Falafel Wrap", description: "Falafel, tortilla, hummus, and salad", category: .mains, price: 10),
                DishTemplate(name: "Grilled Chicken Souvlaki", description: "Grilled chicken with salad and hummus", category: .mains, price: 13),
                DishTemplate(name: "Hummus Plate", description: "Hummus with naan", category: .sides, price: 7),
            ]
        default:
            return []
        }
    }

    private static let cuisineTagByID: [String: String] = [
        "sample:greenfuel": "healthbowl", "sample:freshbowl": "healthbowl",
        "sample:brooklynburger": "american", "sample:burgerbarn": "american",
        "sample:trattoria": "italian",
        "sample:sakura": "japanese", "sample:tokyoramen": "ramen",
        "sample:goldendragon": "chinese",
        "sample:spice": "indian", "sample:casa": "mexican", "sample:bangkok": "thai",
        "sample:cornercafe": "cafe", "sample:olive": "mediterranean",
        // hiddentable intentionally absent → no menu.
    ]

    // MARK: Menu synthesis

    /// Build the full menu for a restaurant. Returns an empty array for places
    /// that publish no readable menu.
    static func menu(for restaurant: Restaurant) -> [MenuItem] {
        guard let tag = cuisineTagByID[restaurant.id] else { return [] }
        let templates = templates(forCuisine: tag, official: restaurant.hasOfficialNutrition)
        return templates.map { makeItem(restaurant: restaurant, template: $0) }
    }

    static func makeItem(restaurant: Restaurant, template: DishTemplate) -> MenuItem {
        let itemID = restaurant.id + ":" + slug(template.name)
        let est = MenuNutritionEstimator.estimate(name: template.name, description: template.description)

        // Deterministic component ids so modifications and saved snapshots stay
        // internally consistent across rebuilds.
        var components = est.components
        for i in components.indices {
            components[i].id = "\(itemID)#\(i)"
        }
        let mods = MenuModificationFactory.standard(for: components)

        var item = MenuItem(
            id: itemID,
            restaurantID: restaurant.id,
            name: template.name,
            itemDescription: template.description,
            category: template.category,
            price: template.price,
            currencyCode: restaurant.currencyCode,
            components: components,
            modifications: mods,
            dietaryTags: est.dietaryTags,
            ingredientHints: est.uncertainTerms,
            defaultOilLevel: est.defaultOilLevel,
            sourceKind: est.sourceKind,
            baseConfidence: est.confidence)

        if template.official {
            // Freeze the estimate as published official nutrition. From here on the
            // resolver treats these numbers as authoritative and never re-estimates
            // oil on top of them.
            let resolved = MenuItemResolver.resolve(item: item)
            item.officialNutrition = resolved.perUnit
            item.sourceKind = .official
            item.baseConfidence = .high
        }
        return item
    }

    static func slug(_ s: String) -> String {
        s.lowercased().map { $0.isLetter || $0.isNumber ? $0 : "-" }.reduce(into: "") { acc, ch in
            if ch == "-" && (acc.isEmpty || acc.hasSuffix("-")) { return }
            acc.append(ch)
        }
    }
}
